# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa94469baae8d14f0c88bbaf1b7105d5d6790e50cc9e47b1d371a5c5fc5fb47c511f84fa829e902fd422e7f9f70294ef481a5a99cf2d589f44c62585ff618095

test:
  secret_key_base: ac2cb97f0f0bc8ebabd226ccd6a27a3d08132dca88088ee19ab3bb77c067ec4494e870810eebf60e85db493cd49c1dc6516e2f19af6b28d407e2aca305b2c565

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
